version: '3'

services:
  migrate:
    build: .
    entrypoint: ./taskcafe migrate
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      - postgres
      - redis
    networks:
      - taskcafe-test
